/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as ComplaintsIdRouteImport } from './routes/complaints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints': typeof ComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/submit' | '/complaints/$id' | '/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/submit' | '/complaints/$id' | '/complaints'
  id:
    '__root__' | '/' | '/about' | '/submit' | '/complaints/$id' | '/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SubmitRoute: typeof SubmitRoute
  ComplaintsIdRoute: typeof ComplaintsIdRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SubmitRoute: SubmitRoute,
  ComplaintsIdRoute: ComplaintsIdRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
